### PR TITLE
Updates package dependencies

### PR DESCRIPTION
**Pull request by kelsos**
Closes #31

### CODE REVIEW

**Comment by LefterisJP** [comment]
Is it required to commit package-lock.json? This commit upgrades ~44 dependencies but due to the package-lock.jzon the diff is 1281 lines long

**Comment by kelsos** [comment]
@LefterisJP I usually ignore it but according to the [documentation](https://docs.npmjs.com/files/package-lock.json) it should be commited

**Comment by LefterisJP** [comment]
To be honest I am not sure why we don't commit it in the webui either. The docs are not convincing me as to why it should be commited, but I am not a node expert.

One thing I am sure about is we should be consistent. Let's commit it in all our projects or not. For now we seem not to, so let's ignore it from here too.

**Comment by kelsos** [comment]
I don't have any idea why it was not committed on the webui, but maybe we should add it if we enable ci?.

**Comment by palango** [comment]
Thanks!

**Pull request merged**
